#! /bin/bash

while :
do
    echo "Enter file name of input file list along with absolute path : "
    read inFileList

    if [ -f $inFileList ]
    then
        cat $inFileList
        break
    else
        echo "File does not exist. Try again."
    fi
done
